[workspace]
resolver = "2"

members = [
    "crates/dengjen/core",
    "crates/dengjen/synth",
    "crates/dengjen/models/piper",
    "crates/dengjen/models/kokoro",
    "crates/frontends/grpc",
    "crates/frontends/python",
    "crates/frontends/capi",
    "crates/frontends/cli",
    "crates/text/espeak-phonemizer",
    "crates/audio/sonic-sys",
    "crates/audio/ops",
]

[patch.crates-io]
libtashkeel_core = { path = "./deps/libtashkeel/crates/core" }

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
